CREATE DATABASE company;

USE company;

CREATE TABLE DEPARTMENT (
    D_NO      VARCHAR(20) PRIMARY KEY,
    DName     VARCHAR(100) NOT NULL,
    ManagerID VARCHAR(20),
    hiredate  DATE
);

CREATE TABLE EMPLOYEE (
    SSN          VARCHAR(20) PRIMARY KEY,
    FName        VARCHAR(50) NOT NULL,
    LName        VARCHAR(50) NOT NULL,
    Gn           VARCHAR(1),
    BD           DATE,
    DNum         VARCHAR(20),
    SupervisorID VARCHAR(20),
    FOREIGN KEY (DNum) REFERENCES DEPARTMENT(D_NO),
    FOREIGN KEY (SupervisorID) REFERENCES EMPLOYEE(SSN)
);

ALTER TABLE DEPARTMENT
    ADD CONSTRAINT fk_department_manager
    FOREIGN KEY (ManagerID) REFERENCES EMPLOYEE(SSN);

CREATE TABLE DEPT_LOCATIONS (
    DNum     VARCHAR(20),
    Location VARCHAR(100),
    PRIMARY KEY (DNum, Location),
    FOREIGN KEY (DNum) REFERENCES DEPARTMENT(D_NO)
);

CREATE TABLE PROJECT (
    PNum     VARCHAR(20) PRIMARY KEY,
    Pname    VARCHAR(100) NOT NULL,
    Location VARCHAR(100),
    City     VARCHAR(100),
    DNum     VARCHAR(20),
    FOREIGN KEY (DNum) REFERENCES DEPARTMENT(D_NO)
);

CREATE TABLE WORKS_ON (
    PNum         VARCHAR(20),
    EmployeeID   VARCHAR(20),
    WorkingHours DECIMAL(5,2),
    PRIMARY KEY (PNum, EmployeeID),
    FOREIGN KEY (PNum) REFERENCES PROJECT(PNum),
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE DEPENDENT (
    SSN   VARCHAR(20),
    DName VARCHAR(100),
    Gn    VARCHAR(1),
    BD    DATE,
    PRIMARY KEY (SSN, DName),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);

ALTER TABLE EMPLOYEE
ADD Salary DECIMAL(10, 2);

ALTER TABLE EMPLOYEE
ADD Address VARCHAR(100);

ALTER TABLE PROJECT
DROP COLUMN CITY;

ALTER TABLE DEPENDENT
ADD RELATIONSHIP VARCHAR(100);
